### PR TITLE
use ignoreIndicatore in every case

### PR DESCRIPTION
**Pull request by TA2k**
should ignoreIndicators use in every case?

### CODE REVIEW

**Comment by TA2k** [comment]
Add modification to recognize yamaha devices via yamaha adapter

**Comment by TA2k** [comment]
Think about to remove read and write checks for buttons because often there are set wrong. Like in hm-rpc
´´´
  button: {
            states: [
                {role: /^button(\.[.\w]+)?$|^action(\.[.\w]+)?$/,           indicator: false, type: 'boolean', read: false, write: true,       name: 'SET',         required: true, noSubscribe: true},
           
´´´

**Comment by TA2k** [comment]
Buttons working like expected
https://github.com/ioBroker/ioBroker.hm-rpc/issues/193

**Comment by GermanBluefox** [comment]
I think I will decline this PR. We discussed it in Telegram.

**Pull request closed without merging**
